"""Document AI: chat + version-safe generation + project rules (batch B10).

Chat over one document, a project folder, or today's context returns an answer
grounded in retrieved passages with citations. Generated outputs are written as
new document versions — the original is never modified.
"""
from __future__ import annotations

import hashlib
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from .db import Document, DocumentChunk, Project, Task
from .retrieval import hybrid_search, to_citations


def chat(
    session: Session,
    query: str,
    project_id: str | None = None,
    document_id: str | None = None,
    limit: int = 5,
) -> dict[str, Any]:
    """Answer a question grounded in retrieved passages (deterministic synthesis).

    Ollabridge phrases the final answer in a later integration; the contract —
    an answer plus citations, or an explicit 'no grounding' — is stable.
    """
    passages = hybrid_search(session, query, project_id=project_id, limit=limit)
    if document_id:
        passages = [p for p in passages if p.document_id == document_id] or passages
    if not passages:
        return {
            "answer": "I couldn't find grounding for that in the indexed documents. "
            "Try granting the source folder or rephrasing.",
            "citations": [],
            "grounded": False,
        }
    # Screen retrieved (untrusted) passages for prompt injection before they
    # would reach an agent's instruction context.
    injection = _scan_passages(passages)

    top = passages[0]
    snippet = top.text.strip().replace("\n", " ")
    answer = (
        f"Based on '{top.document_title}': {snippet[:400]}"
        + ("…" if len(snippet) > 400 else "")
    )
    return {
        "answer": answer,
        "citations": to_citations(passages),
        "grounded": True,
        "injectionFlagged": injection["flagged"],
        "injectionCategories": injection["categories"],
    }


def _scan_passages(passages) -> dict[str, Any]:
    try:
        from daypilot_orchestrator.security.injection_guard import scan
    except Exception:  # pragma: no cover - orchestrator not on path
        return {"flagged": False, "categories": []}
    categories: set[str] = set()
    flagged = False
    for p in passages:
        report = scan(p.text, source=p.document_title)
        if report.flagged:
            flagged = True
            categories.update(report.categories)
    return {"flagged": flagged, "categories": sorted(categories)}


def generate_output(
    session: Session,
    source_document_id: str,
    title: str,
    content: str,
    kind: str = "summary",
) -> dict[str, Any]:
    """Write a generated output as a NEW document version. Never overwrites."""
    source = session.get(Document, source_document_id)
    if source is None:
        raise KeyError(source_document_id)

    # Next version number in this lineage.
    root_id = source.parent_document_id or source.id
    max_version = session.execute(
        select(func.max(Document.version)).where(
            (Document.parent_document_id == root_id) | (Document.id == root_id)
        )
    ).scalar() or 1

    generated = Document(
        owner_user_id=source.owner_user_id,
        project_id=source.project_id,
        source_uri=f"vault://generated/{title}",
        title=title,
        sha256=hashlib.sha256(content.encode("utf-8")).hexdigest(),
        ingest_state="indexed",
        status="Generated by AI",
        source="Generated",
        parent_document_id=root_id,
        version=int(max_version) + 1,
        is_generated=True,
    )
    session.add(generated)
    session.flush()
    for i, chunk in enumerate(_chunk(content)):
        session.add(
            DocumentChunk(document_id=generated.id, chunk_index=i, text=chunk,
                          token_count=max(1, len(chunk.split())), metadata_json={"kind": kind})
        )
    session.flush()
    return {
        "generatedDocumentId": generated.id,
        "sourceDocumentId": source_document_id,
        "version": generated.version,
        "originalPreserved": True,
        "status": generated.status,
    }


def _chunk(text: str, size: int = 1200) -> list[str]:
    clean = text.strip()
    return [clean[i : i + size] for i in range(0, len(clean), size)] if clean else []


# --- Project status rules engine -------------------------------------------

def compute_project_status(session: Session, project: Project) -> dict[str, Any]:
    """Derive progress/risk/blockers/AI-activity from linked tasks and documents."""
    tasks = list(
        session.execute(select(Task).where(Task.project_id == project.id)).scalars()
    )
    total = len(tasks)
    done = sum(1 for t in tasks if t.status == "done")
    blocked = [t.title for t in tasks if t.status == "blocked"]
    running = sum(1 for t in tasks if t.status == "running")
    doc_count = session.execute(
        select(func.count()).select_from(Document).where(Document.project_id == project.id)
    ).scalar() or 0

    progress = round(done / total * 100) if total else project.progress
    if blocked:
        risk = "high" if len(blocked) > 2 else "medium"
    elif running:
        risk = "low"
    else:
        risk = project.risk

    return {
        "projectId": project.id,
        "name": project.name,
        "progress": progress,
        "risk": risk,
        "tasksTotal": total,
        "tasksDone": done,
        "tasksRunning": running,
        "blockers": blocked,
        "documentsLinked": int(doc_count),
        "aiActivity": project.ai_activity,
    }
