export type InstallState =
  | 'INSTALLED_DISABLED'
  | 'REVIEWED'
  | 'ENABLED_FOR_READ_ONLY'
  | 'ENABLED_WITH_APPROVALS'
  | 'ENABLED_AUTONOMOUS_LIMITED'

export type DayPilotPersona = {
  id: string
  label: string
  role: string
  source: 'daypilot' | 'homepilot'
  installState: InstallState
  allowedTools: string[]
}

export type ApprovalRequest = {
  id: string
  personaId: string
  action: string
  risk: 'low' | 'medium' | 'high'
  status: 'pending' | 'approved' | 'rejected'
}

export type DayPilotTaskOwner = 'you' | 'ai' | 'team' | 'system'
export type DayPilotTaskPriority = 'critical' | 'high' | 'medium' | 'low'
export type DayPilotTaskStatus = 'active' | 'running' | 'scheduled' | 'blocked' | 'done' | 'needs_approval'
export type DayPilotRiskLevel = 'low' | 'medium' | 'high'

export type DayPilotTask = {
  id: string
  title: string
  day: 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday'
  start: string
  end: string
  owner: DayPilotTaskOwner
  executor: string
  priority: DayPilotTaskPriority
  status: DayPilotTaskStatus
  context: string
  source?: string
  confidence?: number
  risk?: DayPilotRiskLevel
  projectId?: string
  skipImpact?: string
  parallelAi?: string
  nextAction?: string
}

export type DayPilotMessage = {
  id: string
  role: 'commander' | 'assistant'
  body: string
  createdAt: string
}

export type DayPilotProjectStatus = 'On Track' | 'Active' | 'At Risk' | 'Review' | 'Stable'

export type DayPilotProject = {
  id: string
  name: string
  progress: number
  status: DayPilotProjectStatus
  aiActivity: string
  nextHumanAction: string
  risk: DayPilotRiskLevel
  aiActions: string[]
  designerInput: string[]
  recentSignals: string[]
  linkedSources: string[]
  yesterday: string[]
  today: string[]
  blocked: string[]
  continueAction: string
}

export type DayPilotAgentStatus = 'Running' | 'Needs Approval' | 'Blocked'

export type DayPilotAgent = {
  id: string
  name: string
  currentWork: string
  status: DayPilotAgentStatus
  provider: 'Ollabridge'
  model: string
  mode: 'Local' | 'Hybrid' | 'Cloud'
  latencyMs: number
  detail: string
}

export type DayPilotDocumentStatus =
  | 'Indexed'
  | 'Needs Permission'
  | 'Changed Since Last Review'
  | 'Linked to Today'
  | 'Used by AI'
  | 'Generated by AI'
  | 'Not Yet Indexed'

export type DayPilotDocumentSourceKind = 'Local PC' | 'Box' | 'DayPilot Vault' | 'Project Folder' | 'Generated'
export type DayPilotDocumentPermission = 'Read only' | 'Read + index' | 'Read + generate outputs' | 'Read + write new files'
export type DayPilotDocumentAssistantMode = 'Single Document' | 'Project Folder' | 'Daily Context'

export type DayPilotDocument = {
  id: string
  name: string
  fileType: 'Word' | 'Excel' | 'PowerPoint' | 'PDF' | 'Markdown' | 'Image' | 'Project Data'
  extension: string
  projectId: string
  projectName: string
  source: DayPilotDocumentSourceKind
  status: DayPilotDocumentStatus
  permission: DayPilotDocumentPermission
  updated: string
  usedIn: string
  relevance: string
  changed: string[]
  suggestedActions: string[]
  aiReadableState: string
  originalPreserved: boolean
}

export type DayPilotDocumentSource = {
  id: string
  label: string
  kind: DayPilotDocumentSourceKind
  permission: DayPilotDocumentPermission
  allowed: boolean
  children: string[]
}
