SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

UV ?= uv
PNPM ?= pnpm
API_HOST ?= 0.0.0.0
API_PORT ?= 8080
WEB_PORT ?= 5173

.PHONY: help install install-python install-python-all install-js run run-api run-web run-mobile test lint format typecheck build init-db migrate compose compose-runtime clean preview-persona install-persona

help: ## Show available make targets.
	@awk 'BEGIN {FS = ":.*##"; printf "\nDayPilot Enterprise commands\n\n"} /^[a-zA-Z0-9_.-]+:.*##/ {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
	@printf "\nExamples:\n  make install\n  make run\n  make run-web\n  make test\n\n"

install: install-python install-js ## Install Python and JavaScript dependencies for local development.

install-python: ## Create/sync the UV-managed Python environment with dev tools.
	$(UV) sync --group dev

install-python-all: ## Sync Python with all optional extras for RAG, models, and observability.
	$(UV) sync --all-extras --group dev

install-js: ## Install workspace JavaScript dependencies with pnpm.
	corepack enable
	$(PNPM) install

run: run-api ## Run the default local DayPilot API gateway.

run-api: ## Run the FastAPI API gateway with hot reload.
	$(UV) run uvicorn app.main:app --app-dir services/api-gateway --host $(API_HOST) --port $(API_PORT) --reload

run-web: ## Run the operator web app.
	$(PNPM) --filter @daypilot/operator-web dev -- --host 0.0.0.0 --port $(WEB_PORT)

run-mobile: ## Run the mobile PWA app.
	$(PNPM) --filter @daypilot/mobile-pwa dev -- --host 0.0.0.0

test: ## Run Python tests and package-level JavaScript tests.
	$(UV) run pytest -q
	$(PNPM) -r test

lint: ## Run Python and package-level JavaScript linters.
	$(UV) run ruff check services scripts tests
	$(PNPM) -r lint

format: ## Format Python code with Ruff.
	$(UV) run ruff format services scripts tests

typecheck: ## Run TypeScript builds for workspace packages that define build scripts.
	$(PNPM) -r build

build: ## Build all JavaScript workspace packages/apps.
	$(PNPM) -r build

init-db: ## Initialize the local database.
	$(UV) run python scripts/init_db.py

migrate: ## Apply Alembic migrations.
	$(UV) run alembic upgrade head

compose: ## Start the Docker Compose development stack.
	docker compose up --build

compose-runtime: ## Start runtime and observability Docker Compose profiles.
	docker compose --profile runtime --profile observability up --build

preview-persona: ## Preview the sample HomePilot persona import.
	$(UV) run python scripts/import_homepilot_persona.py examples/homepilot-personas/atlas.hpersona --preview

install-persona: ## Install the sample HomePilot persona import.
	$(UV) run python scripts/import_homepilot_persona.py examples/homepilot-personas/atlas.hpersona --install

clean: ## Remove local caches and virtual environments generated by development commands.
	rm -rf .venv .pytest_cache .ruff_cache
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
