import type { DayPilotAgent, DayPilotDocument, DayPilotDocumentSource, DayPilotMessage, DayPilotProject, DayPilotTask } from '@daypilot/shared-types'

export const initialMessages: DayPilotMessage[] = [
  {
    id: 'msg-001',
    role: 'assistant',
    createdAt: '07:31',
    body:
      'Good morning. I analyzed calendar pressure, priority email, active projects, GitPilot branches, Matrix Designer notes, important documents, and agent status. Today has 3 deep-work blocks, 2 meetings, 1 urgent email thread, 6 linked documents, 4 AI workflows, and 2 project risks. Approve the plan or adjust it here in natural language.',
  },
]

export const initialTasks: DayPilotTask[] = [
  {
    id: 'task-100',
    day: 'Thursday',
    start: '08:00',
    end: '08:30',
    title: 'Inbox scan by Email Sentinel',
    priority: 'medium',
    owner: 'ai',
    executor: 'Email Sentinel',
    status: 'running',
    source: 'Email · priority classifier',
    confidence: 93,
    risk: 'low',
    projectId: 'daypilot-portal',
    nextAction: 'Review only the single thread that may affect the architecture review.',
    parallelAi: 'Classifying urgent reply, schedule impact, project blocker, FYI, and delegate-to-AI threads.',
    skipImpact: 'Urgent email may surface during deep work instead of the planned 09:00 decision window.',
    context:
      'Email Sentinel runs every 10 minutes and summarizes email into actions instead of exposing raw inbox noise.',
  },
  {
    id: 'task-101',
    day: 'Thursday',
    start: '08:30',
    end: '09:00',
    title: 'Daily Command Brief approval',
    priority: 'critical',
    owner: 'you',
    executor: 'You',
    status: 'needs_approval',
    source: 'Calendar + email + projects + agents',
    confidence: 91,
    risk: 'medium',
    nextAction: 'Approve the plan, adjust with chat, or review risks in the drawer.',
    parallelAi: 'Scheduler is holding alternate blocks for GitPilot and Matrix Designer until approval.',
    skipImpact: 'The day will remain in draft mode and agents will continue read-only preparation only.',
    context:
      'Morning launch checkpoint: DayPilot proposes a minute-by-minute plan before changing calendar, tasks, projects, or coding workflows.',
  },
  {
    id: 'task-102',
    day: 'Thursday',
    start: '10:00',
    end: '12:00',
    title: 'Deep Coding Block: API gateway tests',
    priority: 'high',
    owner: 'you',
    executor: 'You + GitPilot Coder',
    status: 'active',
    source: 'GitPilot · branch feature/minimalist-ui',
    confidence: 88,
    risk: 'medium',
    projectId: 'gitpilot-connector',
    nextAction: 'Review the generated patch and approve the PR draft only after test context is clear.',
    parallelAi: 'GitPilot scans PR #42, summarizes failing tests, and drafts a low-risk diff explanation.',
    skipImpact: 'Gateway coverage stays below release threshold and the connector remains at risk.',
    context:
      'Linked coding block with branch, tests, PR draft, risk score, and approval-gated write actions.',
  },
  {
    id: 'task-103',
    day: 'Thursday',
    start: '13:00',
    end: '13:45',
    title: 'Matrix Designer review',
    priority: 'high',
    owner: 'ai',
    executor: 'Matrix Designer',
    status: 'needs_approval',
    source: 'Designer · high-impact suggestions',
    confidence: 86,
    risk: 'low',
    projectId: 'matrix-designer',
    nextAction: 'Approve navigation simplification and card spacing recommendations before design review.',
    parallelAi: 'Designer groups low-priority notes under Projects → Design Notes.',
    skipImpact: 'High-impact UI suggestions may be reviewed too late for the 14:00 project block.',
    context:
      'Design intelligence stays grouped by project and impact; only meaningful suggestions appear in Command.',
  },
  {
    id: 'task-104',
    day: 'Thursday',
    start: '15:00',
    end: '15:45',
    title: 'Project risk resolution',
    priority: 'critical',
    owner: 'team',
    executor: 'You + Project Analyst',
    status: 'scheduled',
    source: 'Projects · risk scoring',
    confidence: 82,
    risk: 'high',
    projectId: 'gitpilot-connector',
    nextAction: 'Review auth boundary and decide whether to move the deadline or reduce scope.',
    parallelAi: 'Project Analyst correlates unread emails, failing tests, and deadline shifts.',
    skipImpact: 'Risk remains unresolved and tomorrow planning starts with two blockers.',
    context:
      'Project-centered review that connects calendar, tasks, GitPilot, designer suggestions, emails, and agents.',
  },
]

export const initialProjects: DayPilotProject[] = [
  {
    id: 'daypilot-portal',
    name: 'DayPilot Portal',
    repository: '',
    progress: 72,
    status: 'On Track',
    aiActivity: '3 AI tasks',
    nextHumanAction: 'Approve daily operating-room layout',
    risk: 'low',
    aiActions: ['Scheduler distributing approved plan', 'Email Sentinel monitoring project blockers', 'Project Analyst updating progress signals'],
    designerInput: ['Reduce visible navigation to five items', 'Move low-priority metrics into drawer', 'Increase spacing in strategy cards'],
    recentSignals: ['1 urgent email thread', 'Daily plan ready for approval', 'Provider latency healthy'],
    linkedSources: ['Command', 'Calendar', 'Tasks', 'Email'],
    yesterday: ['Shipped first enterprise shell pass', 'Mapped daily brief to Command surface'],
    today: ['Start focus mode on UI implementation', 'Review owner clarity in Tasks'],
    blocked: [],
    continueAction: 'Continue now',
  },
  {
    id: 'gitpilot-connector',
    name: 'GitPilot Connector',
    repository: '',
    progress: 48,
    status: 'At Risk',
    aiActivity: '2 blockers',
    nextHumanAction: 'Review auth boundary',
    risk: 'high',
    aiActions: ['GitPilot scanning PR #42', 'Sec-Core checking dependency risk', 'DayPilot scheduling review window'],
    designerInput: ['Simplify workflow labels before review'],
    recentSignals: ['3 unread emails', '2 failing tests', '1 deadline shift'],
    linkedSources: ['GitPilot', 'Projects', 'Calendar', 'Tasks'],
    yesterday: ['Generated patch outline', 'Found failing gateway tests'],
    today: ['Review auth boundary', 'Ask GitPilot to explain patch risk'],
    blocked: ['Auth boundary approval needed'],
    continueAction: 'GitPilot run',
  },
  {
    id: 'matrix-designer',
    name: 'Matrix Designer',
    repository: '',
    progress: 64,
    status: 'Review',
    aiActivity: '5 suggestions',
    nextHumanAction: 'Approve high-impact navigation changes',
    risk: 'medium',
    aiActions: ['Designer analyzing active UI projects', 'DayPilot grouping notes by impact'],
    designerInput: ['Use purple only for autonomous workflows', 'Make drawer the home for low-priority details'],
    recentSignals: ['5 suggestions generated', '2 high-impact suggestions promoted to Command'],
    linkedSources: ['Designer', 'Projects', 'Command'],
    yesterday: ['Captured layout critique', 'Grouped suggestions by impact'],
    today: ['Approve navigation simplification', 'Apply strategy card spacing'],
    blocked: [],
    continueAction: 'Suggestions',
  },
  {
    id: 'homepilot-bridge',
    name: 'HomePilot Bridge',
    repository: '',
    progress: 86,
    status: 'Stable',
    aiActivity: '1 pending',
    nextHumanAction: 'Review next persona import policy',
    risk: 'low',
    aiActions: ['Persona registry validating dependency manifests'],
    designerInput: ['Keep persona policy details behind Settings'],
    recentSignals: ['Read-only import policy active', 'No blocked tools'],
    linkedSources: ['HomePilot', 'Agents', 'Settings'],
    yesterday: ['Validated read-only persona import path'],
    today: ['Monitor persona policy health'],
    blocked: [],
    continueAction: 'Monitor',
  },
  {
    id: 'client-alpha',
    name: 'Client Alpha',
    repository: '',
    progress: 68,
    status: 'On Track',
    aiActivity: '2 AI tasks',
    nextHumanAction: 'Review client proposal',
    risk: 'medium',
    aiActions: ['Email Sentinel drafting follow-up', 'Project Analyst summarizing yesterday notes'],
    designerInput: ['Keep client-facing plan concise'],
    recentSignals: ['Client replied yesterday', 'Proposal needs final review'],
    linkedSources: ['Email', 'Calendar', 'Projects'],
    yesterday: ['Captured client requirements', 'Drafted proposal outline'],
    today: ['Review proposal', 'Prepare meeting summary'],
    blocked: ['Waiting on human approval before sending'],
    continueAction: 'Continue now',
  },
  {
    id: 'internal-automation',
    name: 'Internal Automation',
    repository: '',
    progress: 36,
    status: 'At Risk',
    aiActivity: 'Needs plan',
    nextHumanAction: 'Create recovery plan',
    risk: 'high',
    aiActions: ['Scheduler finding recovery blocks', 'Project Analyst listing blockers'],
    designerInput: ['Move low-priority metrics into drawer'],
    recentSignals: ['No update since yesterday', 'One dependency decision overdue'],
    linkedSources: ['Projects', 'Tasks', 'Agents'],
    yesterday: ['Dependency decision deferred'],
    today: ['Create recovery plan', 'Assign first AI background scan'],
    blocked: ['Dependency owner unclear'],
    continueAction: 'Needs plan',
  },
]


export const documentSources: DayPilotDocumentSource[] = [
  {
    id: 'local-documents',
    label: 'Local Documents',
    kind: 'Local PC',
    permission: 'Read + index',
    allowed: true,
    children: ['Desktop', 'Documents', 'Downloads', 'Selected Project Folders'],
  },
  {
    id: 'box-consulting',
    label: 'Box · Consulting Clients',
    kind: 'Box',
    permission: 'Read + index',
    allowed: true,
    children: ['Consulting Clients', 'Internal Projects', 'Shared Documents'],
  },
  {
    id: 'daypilot-vault',
    label: 'DayPilot Vault',
    kind: 'DayPilot Vault',
    permission: 'Read + generate outputs',
    allowed: true,
    children: ['Recently Used', 'Meeting Files', 'Project Knowledge', 'AI Generated Outputs'],
  },
  {
    id: 'blocked-private',
    label: 'Private folders',
    kind: 'Local PC',
    permission: 'Read only',
    allowed: false,
    children: ['Personal Photos', 'System folders', 'Secrets unless explicitly approved'],
  },
]

export const initialDocuments: DayPilotDocument[] = [
  {
    id: 'doc-proposal-v4',
    name: 'proposal_v4.docx',
    fileType: 'Word',
    extension: '.docx',
    projectId: 'client-alpha',
    projectName: 'Client Alpha',
    source: 'Box',
    status: 'Linked to Today',
    permission: 'Read + index',
    updated: 'Updated yesterday',
    usedIn: '09:00 Client Alpha Review',
    relevance: 'Defines client commitments, pricing, scope, and approval terms for today’s review.',
    changed: ['Pricing section updated', 'Timeline moved from 6 weeks to 8 weeks', 'Deployment support phase added'],
    suggestedActions: ['Summarize', 'Extract tasks', 'Schedule review', 'Create PowerPoint', 'Ask Matrix Designer', 'Link to Project Alpha'],
    aiReadableState: 'Text extracted and indexed; original Word file preserved untouched.',
    originalPreserved: true,
  },
  {
    id: 'doc-budget-forecast',
    name: 'budget_forecast.xlsx',
    fileType: 'Excel',
    extension: '.xlsx',
    projectId: 'client-alpha',
    projectName: 'Client Alpha',
    source: 'Box',
    status: 'Changed Since Last Review',
    permission: 'Read + index',
    updated: 'Updated yesterday',
    usedIn: '09:00 Client Alpha Review',
    relevance: 'Budget assumptions changed and should be reviewed before client follow-up.',
    changed: ['Forecast tab changed', 'Travel line item increased', 'Contingency lowered by 3%'],
    suggestedActions: ['Compare versions', 'Create tasks', 'Summarize risk', 'Open'],
    aiReadableState: 'Tables extracted to internal representation; source workbook will not be overwritten.',
    originalPreserved: true,
  },
  {
    id: 'doc-ui-spec',
    name: 'minimalist_portal_spec.md',
    fileType: 'Markdown',
    extension: '.md',
    projectId: 'daypilot-portal',
    projectName: 'DayPilot Portal',
    source: 'DayPilot Vault',
    status: 'Used by AI',
    permission: 'Read + generate outputs',
    updated: 'Updated today',
    usedIn: '10:00 Deep work: DayPilot frontend',
    relevance: 'Guides the current command-center implementation and document tab layout.',
    changed: ['Documents added as first-class tab', 'Today Context Engine rule added'],
    suggestedActions: ['Summarize this folder', 'Create tasks', 'Make a PowerPoint'],
    aiReadableState: 'Indexed in project memory and available to Document Assistant.',
    originalPreserved: true,
  },
  {
    id: 'doc-designer-notes',
    name: 'matrix_designer_notes.docx',
    fileType: 'Word',
    extension: '.docx',
    projectId: 'matrix-designer',
    projectName: 'Matrix Designer',
    source: 'Project Folder',
    status: 'Indexed',
    permission: 'Read + index',
    updated: 'Updated today',
    usedIn: '14:00 Matrix Designer suggestions',
    relevance: 'Contains UI/UX critique and deck quality notes for today’s design review.',
    changed: ['Navigation recommendation refined', 'Purple usage rule clarified'],
    suggestedActions: ['Ask Matrix Designer', 'Extract design tasks', 'Create report outline'],
    aiReadableState: 'Text extracted; original Office file preserved.',
    originalPreserved: true,
  },
  {
    id: 'doc-roadmap-q3',
    name: 'roadmap_q3.pptx',
    fileType: 'PowerPoint',
    extension: '.pptx',
    projectId: 'internal-automation',
    projectName: 'Internal Automation',
    source: 'Box',
    status: 'Needs Permission',
    permission: 'Read only',
    updated: 'Updated 2 days ago',
    usedIn: '15:00 Internal Strategy',
    relevance: 'Strategy deck may explain the dependency decision blocking automation work.',
    changed: ['Not indexed yet because source needs approval'],
    suggestedActions: ['Grant read + index', 'Create PowerPoint outline', 'Extract blockers'],
    aiReadableState: 'Original file preserved; indexing waiting for permission.',
    originalPreserved: true,
  },
  {
    id: 'doc-mockup',
    name: 'latest_dashboard_mockup.png',
    fileType: 'Image',
    extension: '.png',
    projectId: 'daypilot-portal',
    projectName: 'DayPilot Portal',
    source: 'Project Folder',
    status: 'Linked to Today',
    permission: 'Read + index',
    updated: 'Updated today',
    usedIn: '11:00 DayPilot UI Work',
    relevance: 'Visual reference for spacing, card hierarchy, and document assistant layout.',
    changed: ['New right assistant column', 'Document card actions added'],
    suggestedActions: ['Ask Matrix Designer', 'Summarize visual changes', 'Link to project'],
    aiReadableState: 'Image metadata indexed; visual analysis available through Matrix Designer.',
    originalPreserved: true,
  },
]

export const initialAgents: DayPilotAgent[] = [
  { id: 'scheduler', name: 'DayPilot Scheduler', currentWork: 'Rebalancing', status: 'Running', provider: 'Ollabridge', model: 'fast local model', mode: 'Local', latencyMs: 420, detail: 'Protecting deep-work blocks and holding alternate windows for approvals.' },
  { id: 'gitpilot', name: 'GitPilot Coder', currentWork: 'Patch draft', status: 'Running', provider: 'Ollabridge', model: 'code-specialized model', mode: 'Local', latencyMs: 510, detail: 'Preparing a generated diff summary, failing-test context, and PR draft actions.' },
  { id: 'designer', name: 'Matrix Designer', currentWork: 'UI critique', status: 'Needs Approval', provider: 'Ollabridge', model: 'vision/design model', mode: 'Local', latencyMs: 460, detail: 'Promoted high-impact layout suggestions and parked low-impact notes under Projects.' },
  { id: 'email', name: 'Email Sentinel', currentWork: 'Inbox scan', status: 'Running', provider: 'Ollabridge', model: 'local reasoning model', mode: 'Local', latencyMs: 390, detail: 'Classifying urgent replies, schedule impacts, blockers, FYIs, and delegations every 10 minutes.' },
  { id: 'analyst', name: 'Project Analyst', currentWork: 'Risk scoring', status: 'Blocked', provider: 'Ollabridge', model: 'long-context model', mode: 'Local', latencyMs: 650, detail: 'Waiting for approval to correlate two failing tests with the shifted connector deadline.' },
]

export const weekDays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] as const
export const dayHours = ['08:00', '08:30', '09:00', '10:00', '11:30', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00']
export const weekSlots = ['08:00', '09:00', '10:00', '13:00', '15:00', '17:00']
